"""init

Revision ID: 04c98734fe9b
Revises: 
Create Date: 2026-04-22 17:48:29.766358

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '04c98734fe9b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('backend_error_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_file', sa.String(), nullable=False),
    sa.Column('service_name', sa.String(), nullable=False),
    sa.Column('error_type', sa.String(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('fingerprint', sa.String(), nullable=False),
    sa.Column('stack', sa.Text(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('raw_line', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_backend_error_events_fingerprint'), 'backend_error_events', ['fingerprint'], unique=False)
    op.create_index(op.f('ix_backend_error_events_id'), 'backend_error_events', ['id'], unique=False)
    op.create_table('frontend_error_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('app_id', sa.String(), nullable=False),
    sa.Column('environment', sa.String(), nullable=True),
    sa.Column('release_version', sa.String(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('user_agent', sa.String(), nullable=True),
    sa.Column('error_type', sa.String(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('stack', sa.Text(), nullable=True),
    sa.Column('api_context_json', sa.JSON(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('received_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_frontend_error_events_id'), 'frontend_error_events', ['id'], unique=False)
    op.create_table('incidents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('source_type', sa.String(), nullable=False),
    sa.Column('source_id', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('severity', sa.String(), nullable=False),
    sa.Column('state', sa.String(), nullable=False),
    sa.Column('first_seen', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('last_seen', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_incidents_id'), 'incidents', ['id'], unique=False)
    op.create_index(op.f('ix_incidents_key'), 'incidents', ['key'], unique=True)
    op.create_table('monitor_targets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('method', sa.String(), nullable=True),
    sa.Column('headers_json', sa.JSON(), nullable=True),
    sa.Column('expected_status', sa.Integer(), nullable=True),
    sa.Column('timeout_s', sa.Integer(), nullable=True),
    sa.Column('interval_s', sa.Integer(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_monitor_targets_id'), 'monitor_targets', ['id'], unique=False)
    op.create_table('alert_deliveries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('incident_id', sa.Integer(), nullable=True),
    sa.Column('alert_type', sa.String(), nullable=False),
    sa.Column('recipient', sa.String(), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=True),
    sa.Column('error_msg', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alert_deliveries_id'), 'alert_deliveries', ['id'], unique=False)
    op.create_index(op.f('ix_alert_deliveries_incident_id'), 'alert_deliveries', ['incident_id'], unique=False)
    op.create_table('endpoint_check_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('http_code', sa.Integer(), nullable=True),
    sa.Column('error_class', sa.String(), nullable=True),
    sa.Column('response_ms', sa.Float(), nullable=True),
    sa.Column('checked_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['target_id'], ['monitor_targets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_endpoint_check_results_id'), 'endpoint_check_results', ['id'], unique=False)
    op.create_index(op.f('ix_endpoint_check_results_target_id'), 'endpoint_check_results', ['target_id'], unique=False)
    op.create_table('incident_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('incident_id', sa.Integer(), nullable=True),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('detail_json', sa.JSON(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_incident_events_id'), 'incident_events', ['id'], unique=False)
    op.create_index(op.f('ix_incident_events_incident_id'), 'incident_events', ['incident_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_incident_events_incident_id'), table_name='incident_events')
    op.drop_index(op.f('ix_incident_events_id'), table_name='incident_events')
    op.drop_table('incident_events')
    op.drop_index(op.f('ix_endpoint_check_results_target_id'), table_name='endpoint_check_results')
    op.drop_index(op.f('ix_endpoint_check_results_id'), table_name='endpoint_check_results')
    op.drop_table('endpoint_check_results')
    op.drop_index(op.f('ix_alert_deliveries_incident_id'), table_name='alert_deliveries')
    op.drop_index(op.f('ix_alert_deliveries_id'), table_name='alert_deliveries')
    op.drop_table('alert_deliveries')
    op.drop_index(op.f('ix_monitor_targets_id'), table_name='monitor_targets')
    op.drop_table('monitor_targets')
    op.drop_index(op.f('ix_incidents_key'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_id'), table_name='incidents')
    op.drop_table('incidents')
    op.drop_index(op.f('ix_frontend_error_events_id'), table_name='frontend_error_events')
    op.drop_table('frontend_error_events')
    op.drop_index(op.f('ix_backend_error_events_id'), table_name='backend_error_events')
    op.drop_index(op.f('ix_backend_error_events_fingerprint'), table_name='backend_error_events')
    op.drop_table('backend_error_events')
    # ### end Alembic commands ###
